services:
  # rtsp-server:
  #   image: bluenviron/mediamtx:latest
  #   container_name: rtsp-server
  #   ports:
  #     - "8554:8554"      # RTSP port
  #     - "1935:1935"      # RTMP port (optional)
  #     - "8888:8888"      # HTTP stream (optional)
  #   volumes:
  #     - ./mediamtx.yml:/mediamtx.yml
  #     - ./data/cam_videos:/videos
  #   restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  detection:
    build: .
    container_name: detection
    environment:
      PIKA_ROUTING_KEY: ${PIKA_ROUTING_KEY}
      PIKA_USER: ${PIKA_USER}
      PIKA_PASS: ${PIKA_PASS}
      PIKA_HOST: rabbitmq
