services:
  rtsp-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    ports:
      - "8554:8554"      # RTSP port
      - "1935:1935"      # RTMP port (optional)
      - "8888:8888"      # HTTP stream (optional)
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
      - ./data/cam_videos:/videos:ro
    restart: unless-stopped

  ffmpeg-streamer:
    image: jrottenberg/ffmpeg:7.1-scratch
    depends_on:
      - rtsp-server
    volumes:
      - ./data/cam_videos:/videos:ro
    command: >
      -re -stream_loop -1 -i /videos/1.mp4
      -c copy -f rtsp rtsp://rtsp-server:8554/cam
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
